const questionsroutine = [
    {
        id: 1,
        type: "sentence",
        title: "完整的日常工作生活",
        content: `<div class="p-4 font-mono text-sm">
                    <div>After getting up every day, I first finish my morning routines such as <span class="code-blank" data-id="1-1" data-answer="using"></span> the toilet and <span class="code-blank" data-id="1-2" data-answer="washing"></span> up. Then I go downstairs and <span class="code-blank" data-id="1-3" data-answer="take"></span> the bus to the company, with one <span class="code-blank" data-id="1-4" data-answer="transfer"></span> on the way, and usually arrive at work on <span class="code-blank" data-id="1-5" data-answer="time"></span> at 9 o'clock. Upon reaching the office, I <span class="code-blank" data-id="1-6" data-answer="put"></span> down my backpack first, <span class="code-blank" data-id="1-7" data-answer="browse"></span> on my personal computer for a while, and then <span class="code-blank" data-id="1-8" data-answer="head"></span> to the laboratory to turn on the company computer. I check the issues I raised <span class="code-blank" data-id="1-9" data-answer="earlier"></span> and confirm if there is anything that needs <span class="code-blank" data-id="1-10" data-answer="re-testing"></span>. If re-testing is required, I go to the <span class="code-blank" data-id="1-11" data-answer="test"></span> bench to carry out the test work, and at the same time prepare for the meeting with the leaders and the <span class="code-blank" data-id="1-12" data-answer="German"></span> team. Around 11:30, I ask my colleagues to go for <span class="code-blank" data-id="1-13" data-answer="lunch"></span> together. We discuss and choose a dining <span class="code-blank" data-id="1-14" data-answer="spot"></span>, order the dishes, and sometimes wait for the food to be served. After the meal, we settle the bill, <span class="code-blank" data-id="1-15" data-answer="wipe"></span> our mouths, then take a walk with colleagues to aid <span class="code-blank" data-id="1-16" data-answer="digestion"></span> before going back to the company together. Once back at the company, I take a short nap on the desk either in the laboratory or the <span class="code-blank" data-id="1-17" data-answer="office"></span>, and then get up promptly at 1 p.m. to continue <span class="code-blank" data-id="1-18" data-answer="working"></span>. I work until 5:30 p.m., then <span class="code-blank" data-id="1-19" data-answer="pack"></span> up my things and take the bus <span class="code-blank" data-id="1-20" data-answer="home"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子",
        hint: "动词、名词和短语",
        explanation: "描述从起床到下班回家的完整日常工作生活流程",
        fullSentence: "After getting up every day, I first finish my morning routines such as using the toilet and washing up. Then I go downstairs and take the bus to the company, with one transfer on the way, and usually arrive at work on time at 9 o'clock. Upon reaching the office, I put down my backpack first, browse on my personal computer for a while, and then head to the laboratory to turn on the company computer. I check the issues I raised earlier and confirm if there is anything that needs re-testing. If re-testing is required, I go to the test bench to carry out the test work, and at the same time prepare for the meeting with the leaders and the German team. Around 11:30, I ask my colleagues to go for lunch together. We discuss and choose a dining spot, order the dishes, and sometimes wait for the food to be served. After the meal, we settle the bill, wipe our mouths, then take a walk with colleagues to aid digestion before going back to the company together. Once back at the company, I take a short nap on the desk either in the laboratory or the office, and then get up promptly at 1 p.m. to continue working. I work until 5:30 p.m., then pack up my things and take the bus home."
    },
    {
        id: 2,
        type: "sentence",
        title: "完整的日常工作生活（德语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Jeden Tag, nachdem ich aufstehe, beende ich zuerst meine morgendlichen Routinen wie das <span class="code-blank" data-id="2-1" data-answer="Benutzen"></span> der Toilette und das <span class="code-blank" data-id="2-2" data-answer="Waschen"></span>. Dann gehe ich die Treppe runter und <span class="code-blank" data-id="2-3" data-answer="nehme"></span> den Bus zur Firma, mit einer <span class="code-blank" data-id="2-4" data-answer="Umsteigung"></span> unterwegs, und arriveere normalerweise pünktlich um 9 Uhr zur Arbeit. Beim Erreichen des Büros lege ich zuerst meinen Rucksack <span class="code-blank" data-id="2-5" data-answer="ab"></span>, surfe eine Weile auf meinem persönlichen Computer, und gehe dann zum <span class="code-blank" data-id="2-6" data-answer="Labor"></span>, um den Firmencomputer einzuschalten. Ich überprüfe die Probleme, die ich früher gestellt <span class="code-blank" data-id="2-7" data-answer="habe"></span>, und bestätige, ob etwas erneut getestet werden muss. Wenn eine erneute Prüfung erforderlich ist, gehe ich zum <span class="code-blank" data-id="2-8" data-answer="Prüfstand"></span>, um die Prüfarbeit durchzuführen, und bereite gleichzeitig das Treffen mit den Leitern und dem <span class="code-blank" data-id="2-9" data-answer="deutschen"></span> Team vor. Um etwa 11:30 Uhr bitte ich meine Kollegen, gemeinsam zum <span class="code-blank" data-id="2-10" data-answer="Mittagessen"></span> zu gehen. Wir diskutieren und wählen einen Essort, bestellen die Gerichte und warten manchmal auf das <span class="code-blank" data-id="2-11" data-answer="Essen"></span>. Nach dem Essen bezahlen wir die <span class="code-blank" data-id="2-12" data-answer="Rechnung"></span>, wischen uns den Mund, gehen dann mit Kollegen spazieren, um die <span class="code-blank" data-id="2-13" data-answer="Verdauung"></span> zu unterstützen, bevor wir gemeinsam zurück zur Firma gehen. Zurück bei der Firma mache ich einen kurzen Schläfchen auf dem Schreibtisch entweder im Labor oder im <span class="code-blank" data-id="2-14" data-answer="Büro"></span> und stehe dann um 13 Uhr pünktlich auf, um weiterzuarbeiten. Ich arbeite bis 17:30 Uhr, packe dann meine Sachen <span class="code-blank" data-id="2-15" data-answer="zusammen"></span> und nehme den Bus nach <span class="code-blank" data-id="2-16" data-answer="Hause"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（德语）",
        hint: "动词、名词和短语",
        explanation: "Beschreibt den kompletten Alltag vom Aufstehen bis zum Heimkommen von der Arbeit",
        fullSentence: "Jeden Tag, nachdem ich aufstehe, beende ich zuerst meine morgendlichen Routinen wie das Benutzen der Toilette und das Waschen. Dann gehe ich die Treppe runter und nehme den Bus zur Firma, mit einer Umsteigung unterwegs, und arriveere normalerweise pünktlich um 9 Uhr zur Arbeit. Beim Erreichen des Büros lege ich zuerst meinen Rucksack ab, surfe eine Weile auf meinem persönlichen Computer, und gehe dann zum Labor, um den Firmencomputer einzuschalten. Ich überprüfe die Probleme, die ich früher gestellt habe, und bestätige, ob etwas erneut getestet werden muss. Wenn eine erneute Prüfung erforderlich ist, gehe ich zum Prüfstand, um die Prüfarbeit durchzuführen, und bereite gleichzeitig das Treffen mit den Leitern und dem deutschen Team vor. Um etwa 11:30 Uhr bitte ich meine Kollegen, gemeinsam zum Mittagessen zu gehen. Wir diskutieren und wählen einen Essort, bestellen die Gerichte und warten manchmal auf das Essen. Nach dem Essen bezahlen wir die Rechnung, wischen uns den Mund, gehen dann mit Kollegen spazieren, um die Verdauung zu unterstützen, bevor wir gemeinsam zurück zur Firma gehen. Zurück bei der Firma mache ich einen kurzen Schläfchen auf dem Schreibtisch entweder im Labor oder im Büro und stehe dann um 13 Uhr pünktlich auf, um weiterzuarbeiten. Ich arbeite bis 17:30 Uhr, packe dann meine Sachen zusammen und nehme den Bus nach Hause."
    },
    {
        id: 3,
        type: "sentence",
        title: "完整的日常工作生活（阿拉伯语）",
        content: `<div class="p-4 font-mono text-sm" dir="rtl">
                    <div>كل يوم بعد الاستيقاظ، أنجز أولاً روتيني الصباحية مثل <span class="code-blank" data-id="3-1" data-answer="استخدام"></span> الحمام و <span class="code-blank" data-id="3-2" data-answer="الغسل"></span>. ثم أنزل السلالم وأنا <span class="code-blank" data-id="3-3" data-answer="أستخدم"></span> الحافلة إلى الشركة، مع نقطة تحويل واحدة على الطريق، وعادة ما أصل إلى العمل في الوقت المحدد الساعة 9 صباحًا. عند الوصول إلى المكتب، أضع حقيبتي الظهرية أولاً، وأتصفح على جهاز الكمبيوتر الخاص بي لفترة من الوقت، ثم أذهب إلى <span class="code-blank" data-id="3-4" data-answer="المختبر"></span> لفتح جهاز الكمبيوتر الخاص بالشركة. أفحص المشكلات التي طرحتها سابقًا وأؤكد ما إذا كان هناك أي شيء يحتاج إلى اختبار مرة أخرى. إذا كانت هناك حاجة إلى اختبار مرة أخرى، أذهب إلى <span class="code-blank" data-id="3-5" data-answer="محطة الاختبار"></span> لإجراء العملية الاختبارية، وإذا كان هناك حاجة إلى اختبار مرة أخرى، وأستعد في نفس الوقت للمؤتمر مع الرؤساء وفريق <span class="code-blank" data-id="3-6" data-answer="الألماني"></span>. حوالي الساعة 11:30، أسأل زملائي للذهاب إلى <span class="code-blank" data-id="3-7" data-answer="الغداء"></span> معًا. نناقش ونختار مكانًا لتناول الطعام، ونطلب الأطباق، وأنتظر أحيانًا حتى يتم تقديم الطعام. بعد الوجبة، نقوم بسداد الفاتورة، ونمسح أفواهنا، ثم نذهب لمشي مع زملائنا للمساعدة على <span class="code-blank" data-id="3-8" data-answer="الهضم"></span> قبل العودة إلى الشركة معًا. بمجرد العودة إلى الشركة، أخذ قيلولة قصيرة على المكتب إما في المختبر أو في <span class="code-blank" data-id="3-9" data-answer="المكتب"></span>، ثم أستيقظ على الفور الساعة 1 مساءً للمتابعة في <span class="code-blank" data-id="3-10" data-answer="العمل"></span>. أعمل حتى الساعة 5:30 مساءً، ثم أحزم أغراضي وأستخدم الحافلة للعودة إلى <span class="code-blank" data-id="3-11" data-answer="المنزل"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（阿拉伯语）",
        hint: "الإ глаات، الأسماء والعبارات",
        explanation: "يصف سير عمل يومي كامل من الاستيقاظ حتى العودة إلى المنزل من العمل",
        fullSentence: "كل يوم بعد الاستيقاظ، أنجز أولاً روتيني الصباحية مثل استخدام الحمام والغسل. ثم أنزل السلالم وأنا أستخدم الحافلة إلى الشركة، مع نقطة تحويل واحدة على الطريق، وعادة ما أصل إلى العمل في الوقت المحدد الساعة 9 صباحًا. عند الوصول إلى المكتب، أضع حقيبتي الظهرية أولاً، وأتصفح على جهاز الكمبيوتر الخاص بي لفترة من الوقت， ثم أذهب إلى المختبر لفتح جهاز الكمبيوتر الخاص بالشركة. أفحص المشكلات التي طرحتها سابقًا وأؤكد ما إذا كان هناك أي شيء يحتاج إلى اختبار مرة أخرى. إذا كانت هناك حاجة إلى اختبار مرة أخرى， أذهب إلى محطة الاختبار لإجراء العملية الاختبارية، وإذا كان هناك حاجة إلى اختبار مرة أخرى， وأستعد في نفس الوقت للمؤتمر مع الرؤساء وفريق الألماني. حوالي الساعة 11:30، أسأل زملائي للذهاب إلى الغداء معًا. نناقش ونختار مكانًا لتناول الطعام، ونطلب الأطباق، وأنتظر أحيانًا حتى يتم تقديم الطعام. بعد الوجبة، نقوم بسداد الفاتورة، ونمسح أفواهنا، ثم نذهب لمشي مع زملائنا للمساعدة على الهضم قبل العودة إلى الشركة معًا. بمجرد العودة إلى الشركة، أخذ قيلولة قصيرة على المكتب إما في المختبر أو في المكتب، ثم أستيقظ على الفور الساعة 1 مساءً للمتابعة في العمل. أعمل حتى الساعة 5:30 مساءً، ثم أحزم أغراضي وأستخدم الحافلة للعودة إلى المنزل."
    },
    {
        id: 4,
        type: "sentence",
        title: "完整的日常工作生活（日语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>毎日起床後、最初に <span class="code-blank" data-id="4-1" data-answer="トイレ"></span>を使ったり、洗顔をするなどの朝のルーティンを終えます。その後階段を降りて、バスで会社に行きます。途中1回 <span class="code-blank" data-id="4-2" data-answer="乗り換え"></span>をして、通常9時に時間通りに出勤します。オフィスに到着すると、最初にバックパックを置いて、パソコンでしばらく <span class="code-blank" data-id="4-3" data-answer="ブラウジング"></span>をしてから、研究所に行って会社のコンピュータを <span class="code-blank" data-id="4-4" data-answer="起動"></span>します。以前に提出した問題点を確認し、再テストが必要なものがあるかどうかを確認します。再テストが必要な場合は、テストベンチに行ってテスト作業を行い、同時にリーダーや <span class="code-blank" data-id="4-5" data-answer="ドイツ"></span>チームとの会議の準備をします。午前11時30分頃、同僚に一緒に <span class="code-blank" data-id="4-6" data-answer="昼食"></span>に行こうと誘います。私たちは協議して食事の場所を選び、料理を注文して、時々料理が出るのを待ちます。食事の後、会計を清算し、口を拭いてから、同僚と一緒に <span class="code-blank" data-id="4-7" data-answer="消化"></span>を助けるために散歩をしてから、一緒に会社に戻ります。会社に戻ったら、研究所またはオフィスのデスクで短い昼寝をして、午後1時にすぐに起きて仕事を続けます。午後5時半まで仕事をしてから、荷物をまとめてバスで <span class="code-blank" data-id="4-8" data-answer="家"></span>に帰ります。</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（日语）",
        hint: "名詞、動詞とフレーズ",
        explanation: "起床から仕事を終えて家に帰るまでの完全な日常業務生活の流れを説明する",
        fullSentence: "毎日起床後、最初にトイレを使ったり、洗顔をするなどの朝のルーティンを終えます。その後階段を降りて、バスで会社に行きます。途中1回乗り換えをして、通常9時に時間通りに出勤します。オフィスに到着すると、最初にバックパックを置いて、パソコンでしばらくブラウジングをしてから、研究所に行って会社のコンピュータを起動します。以前に提出した問題点を確認し、再テストが必要なものがあるかどうかを確認します。再テストが必要な場合は、テストベンチに行ってテスト作業を行い、同時にリーダーやドイツチームとの会議の準備をします。午前11時30分頃、同僚に一緒に昼食に行こうと誘います。私たちは協議して食事の場所を選び、料理を注文して、時々料理が出るのを待ちます。食事の後、会計を清算し、口を拭いてから、同僚と一緒に消化を助けるために散歩をしてから、一緒に会社に戻ります。会社に戻ったら、研究所またはオフィスのデスクで短い昼寝をして、午後1時にすぐに起きて仕事を続けます。午後5時半まで仕事をしてから、荷物をまとめてバスで家に帰ります。"
    },
    {
        id: 5,
        type: "sentence",
        title: "完整的日常工作生活（韩语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>매일 아침 일어난 후, 먼저 화장실을 <span class="code-blank" data-id="5-1" data-answer="이용"></span>하거나 세안을 하는 등 아침 루틴을 마칩니다. 그 후 계단을 내려 버스를 타고 회사로 가는데,途中 한 번 <span class="code-blank" data-id="5-2" data-answer="환승"></span>을 하고, 보통 9시에 시간에 맞춰 출근합니다. 사무실에 도착하면, 먼저 백팩을 내려놓고 개인 컴퓨터에서 잠시 <span class="code-blank" data-id="5-3" data-answer="브라우징"></span>을 한 후 연구실로 가서 회사 컴퓨터를 켭니다. 예전에 제기한 문제를 확인하고, <span class="code-blank" data-id="5-4" data-answer="재테스트"></span>가 필요한 것들이 있는지 확인합니다. 재테스트가 필요한 경우 테스트 벤치로 가서 테스트 작업을 수행하고, 동시에 리더와 독일 팀과의 회의 <span class="code-blank" data-id="5-5" data-answer="준비"></span>를 합니다. 오전 11시 30분쯤, 동료들에게 같이 점심을 먹으러 가자고 요청합니다. 우리는 논의하고 식사 장소를 선택하고 메뉴를 주문하고 때로는 음식이 나올 때까지 기다립니다. 식사 후 계산을 정산하고 입을 닦은 후, 동료들과 함께 소화를 돕기 위해 <span class="code-blank" data-id="5-6" data-answer="산책"></span>을 한 뒤 함께 회사로 돌아옵니다. 회사에 돌아오면 연구실이나 사무실의 책상에서 짧은 낮잠을 자고, 오후 1시에 즉시 일어나 계속 일합니다. 저녁 5시 30분까지 일한 후 물건을收拾하고 버스를 타고 집에 돌아갑니다.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（韩语）",
        hint: "동사, 명사 및 구",
        explanation: "일어나서 퇴근까지의 일상 생활을 설명합니다",
        fullSentence: "매일 아침 일어난 후, 먼저 화장실을 이용하거나 세안을 하는 등 아침 루틴을 마칩니다. 그 후 계단을 내려 버스를 타고 회사로 가는데,途中 한 번 환승을 하고, 보통 9시에 시간에 맞춰 출근합니다. 사무실에 도착하면, 먼저 백팩을 내려놓고 개인 컴퓨터에서 잠시 브라우징을 한 후 연구실로 가서 회사 컴퓨터를 켭니다. 예전에 제기한 문제를 확인하고, 재테스트가 필요한 것들이 있는지 확인합니다. 재테스트가 필요한 경우 테스트 벤치로 가서 테스트 작업을 수행하고, 동시에 리더와 독일 팀과의 회의 준비를 합니다. 오전 11시 30분쯤, 동료들에게 같이 점심을 먹으러 가자고 요청합니다. 우리는 논의하고 식사 장소를 선택하고 메뉴를 주문하고 때로는 음식이 나올 때까지 기다립니다. 식사 후 계산을 정산하고 입을 닦은 후, 동료들과 함께 소화를 돕기 위해 산책을 한 뒤 함께 회사로 돌아옵니다. 회사에 돌아오면 연구실이나 사무실의 책상에서 짧은 낮잠을 자고, 오후 1시에 즉시 일어나 계속 일합니다. 저녁 5시 30분까지 일한 후 물건을收拾하고 버스를 타고 집에 돌아갑니다."
    },
    {
        id: 6,
        type: "sentence",
        title: "完整的日常工作生活（俄语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Каждый день, после того как я встаю, я сначала завершаю свою утреннюю рутину, такую как <span class="code-blank" data-id="6-1" data-answer="использование"></span> туалета иумывание. Затем я спускаюсь по лестнице и еду на автобусе до офиса с одной пересадкой на пути, и обычно прихожу вовремя на работу в 9 утра. При прибытии в офис я сначала оставляю рюкзак, немного <span class="code-blank" data-id="6-2" data-answer="браузеру"></span> по своему личному компьютеру, а затем иду в лабораторию, чтобы включить корпоративный компьютер. Я проверяю проблемы, которые я поднял раньше, и подтверждаю, нужно ли что-то <span class="code-blank" data-id="6-3" data-answer="повторно протестировать"></span>. Если требуется повторное тестирование, я иду на стенд, чтобы провести тестовую работу, и одновременно готовлюсь к встрече с лидерами и немецкой командой. Около 11:30 я прошу своих коллег пойти с меня на обед. Мы обсуждаем и выбираем тип питания, заказываем блюда и иногда ждем еду. После еды мы оплачиваем счет, вытираем рты, а затем гуляем с коллегами, чтобы помочь пищеварению, прежде чем вместе вернутся в офис. Вернувшись в офис, я немного сплю за своим столом либо в лаборатории, либо в офисе, а затем встаю ровно в 13:00, чтобы продолжить работу. Я работаю до 17:30, затем собираю свои вещи и еду на автобусе домой.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（俄语）",
        hint: "глаголы, существительные и фразы",
        explanation: "Описывает полный повседневный день от пробуждения до возвращения с работы домой",
        fullSentence: "Каждый день, после того как я встаю, я сначала завершаю свою утреннюю рутину, такую как использование туалета иумывание. Затем я спускаюсь по лестнице и еду на автобусе до офиса с одной пересадкой на пути, и обычно прихожу вовремя на работу в 9 утра. При прибытии в офис я сначала оставляю рюкзак, немного браузеру по своему личному компьютеру, а затем иду в лабораторию, чтобы включить корпоративный компьютер. Я проверяю проблемы, которые я поднял раньше, и подтверждаю, нужно ли что-то повторно протестировать. Если требуется повторное тестирование, я иду на стенд, чтобы провести тестовую работу, и одновременно готовлюсь к встрече с лидерами и немецкой командой. Около 11:30 я прошу своих коллег пойти с меня на обед. Мы обсуждаем и выбираем тип питания, заказываем блюда и иногда ждем еду. После еды мы оплачиваем счет, вытираем рты, а затем гуляем с коллегами, чтобы помочь пищеварению, прежде чем вместе вернутся в офис. Вернувшись в офис, я немного сплю за своим столом либо в лаборатории, либо в офисе, а затем встаю ровно в 13:00, чтобы продолжить работу. Я работаю до 17:30, затем собираю свои вещи и еду на автобусе домой."
    },
    {
        id: 7,
        type: "sentence",
        title: "完整的日常工作生活（西班牙语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Cada día, después de despertarme, primero termino mi rutina matutina como usar el baño y lavarme. Luego bajo las escaleras y tomo el autobús a la empresa, con una <span class="code-blank" data-id="7-1" data-answer="transbordo"></span> en el camino, y generalmente llego puntualmente a las 9 en punto para el trabajo. Al llegar a la oficina, primero dejo mi mochila, navego un poco en mi computadora personal y luego voy al laboratorio para encender la computadora de la empresa. Reviso los problemas que plantee anteriormente y confirma si hay algo que necesite probar <span class="code-blank" data-id="7-2" data-answer="nuevamente"></span>. Si se necesita una prueba adicional, voy a la mesa de prueba para realizar el trabajo de prueba y al mismo tiempo preparo la reunión con los líderes y el equipo alemán. Alrededor de las 11:30, invito a mis compañeros a ir a almorzar juntos. Discutimos y elegimos un tipo de comida, pedimos los platos y a veces esperamos la comida. Después de comer, pagamos la cuenta, nos limpiamos la boca y luego paseamos con los compañeros para ayudar a la digestión antes de regresar juntos a la empresa. Al regresar a la empresa, tomo una breve siesta en mi escritorio, ya sea en el laboratorio o en la oficina, y luego me levanto puntualmente a las 13:00 para continuar trabajando. Trabajo hasta las 17:30, luego recojo mis cosas y tomo el autobús a <span class="code-blank" data-id="7-3" data-answer="casa"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（西班牙语）",
        hint: "verbos, sustantivos y frases",
        explanation: "Describe una vida diaria completa desde que te levantas hasta que vuelves a casa del trabajo",
        fullSentence: "Cada día, después de despertarme, primero termino mi rutina matutina como usar el baño y lavarme. Luego bajo las escaleras y tomo el autobús a la empresa, con una transbordo en el camino, y generalmente llego puntualmente a las 9 en punto para el trabajo. Al llegar a la oficina, primero dejo mi mochila, navego un poco en mi computadora personal y luego voy al laboratorio para encender la computadora de la empresa. Reviso los problemas que plantee anteriormente y confirma si hay algo que necesite probar nuevamente. Si se necesita una prueba adicional, voy a la mesa de prueba para realizar el trabajo de prueba y al mismo tiempo preparo la reunión con los líderes y el equipo alemán. Alrededor de las 11:30, invito a mis compañeros a ir a almorzar juntos. Discutimos y elegimos un tipo de comida, pedimos los platos y a veces esperamos la comida. Después de comer, pagamos la cuenta, nos limpiamos la boca y luego paseamos con los compañeros para ayudar a la digestión antes de regresar juntos a la empresa. Al regresar a la empresa, tomo una breve siesta en mi escritorio, ya sea en el laboratorio o en la oficina, y luego me levanto puntualmente a las 13:00 para continuar trabajando. Trabajo hasta las 17:30, luego recojo mis cosas y tomo el autobús a casa."
    },
    {
        id: 8,
        type: "sentence",
        title: "完整的日常工作生活（法语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Chaque jour, après m'être réveillé, je termine d'abord ma routine matinale comme utiliser les toilettes et me laver. Ensuite, je descends l'escalier et prends le bus pour l'entreprise, avec un <span class="code-blank" data-id="8-1" data-answer="correspondance"></span> en cours de route, et j'arrive généralement à l'heure pour le travail à 9 heures. En arrivant au bureau, je dépose d'abord mon sac à dos, surfe un peu sur mon ordinateur personnel, puis vais au laboratoire pour allumer l'ordinateur de l'entreprise. Je vérifie les problèmes que j'ai soulevés précédemment et confirme s'il y a quelque chose qui doit être testé <span class="code-blank" data-id="8-2" data-answer="à nouveau"></span>. Si un nouveau test est nécessaire, je vais au banc d'essai pour effectuer le travail d'essai et préparer en même temps la réunion avec les dirigeants et l'équipe allemande. Vers 11h30, je demande à mes collègues d'aller déjeuner ensemble. Nous discutons et choisissons un type de nourriture, commandons les plats et attendons parfois la nourriture. Après le repas, nous payons l'addition, nous essuyons la bouche, puis nous promenons avec des collègues pour aider à la digestion avant de retourner ensemble à l'entreprise. En retournant à l'entreprise, je prends une courte sieste sur mon bureau, soit dans le laboratoire, soit dans le bureau, et ensuite je me lève à l'heure à 13 heures pour continuer à travailler. Je travaille jusqu'à 17h30, puis je ramasse mes affaires et prends le bus pour <span class="code-blank" data-id="8-3" data-answer="ma maison"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（法语）",
        hint: "verbes, noms et phrases",
        explanation: "Décrit une vie quotidienne complète du lever au retour à la maison du travail",
        fullSentence: "Chaque jour, après m'être réveillé, je termine d'abord ma routine matinale comme utiliser les toilettes et me laver. Ensuite, je descends l'escalier et prends le bus pour l'entreprise, avec un correspondance en cours de route, et j'arrive généralement à l'heure pour le travail à 9 heures. En arrivant au bureau, je dépose d'abord mon sac à dos, surfe un peu sur mon ordinateur personnel, puis vais au laboratoire pour allumer l'ordinateur de l'entreprise. Je vérifie les problèmes que j'ai soulevés précédemment et confirme s'il y a quelque chose qui doit être testé à nouveau. Si un nouveau test est nécessaire, je vais au banc d'essai pour effectuer le travail d'essai et préparer en même temps la réunion avec les dirigeants et l'équipe allemande. Vers 11h30, je demande à mes collègues d'aller déjeuner ensemble. Nous discutons et choisissons un type de nourriture, commandons les plats et attendons parfois la nourriture. Après le repas, nous payons l'addition, nous essuyons la bouche, puis nous promenons avec des collègues pour aider à la digestion avant de retourner ensemble à l'entreprise. En retournant à l'entreprise, je prends une courte sieste sur mon bureau, soit dans le laboratoire, soit dans le bureau, et ensuite je me lève à l'heure à 13 heures pour continuer à travailler. Je travaille jusqu'à 17h30, puis je ramasse mes affaires et prends le bus pour ma maison."
    },
    {
        id: 9,
        type: "sentence",
        title: "完整的日常工作生活（意大利语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Ogni giorno, dopo essermi svegliato, termino prima la mia routine mattutina come usare il bagno e lavarmi. Quindi scendo le scale e prendo l'autobus per l'azienda, con una <span class="code-blank" data-id="9-1" data-answer="corse"></span> in strada, e generalmente arrivo in tempo per il lavoro alle 9. Arrivando in ufficio, depongo prima lo zaino, navigo un po' sul mio computer personale, poi vado nel laboratorio per accendere il computer aziendale. Verifico i problemi che ho sollevato in precedenza e confermo se c'è qualcosa che deve essere testato di <span class="code-blank" data-id="9-2" data-answer="nuovo"></span>. Se è necessario un nuovo test, vado al banco di prova per svolgere il lavoro di prova e preparare contemporaneamente l'incontro con i capi e il team tedesco. Verso le 11:30, chiedo ai miei colleghi di andare a pranzo insieme. Discutiamo e scegliamo un tipo di cibo, ordinamo i piatti e a volte aspettiamo il cibo. Dopo il pasto, paghiamo il conto, asciughiamo la bocca, poi camminiamo con i colleghi per aiutare la digestione prima di tornare insieme all'azienda. Tornando all'azienda, faccio una breve pisolino sulla mia scrivania, sia nel laboratorio che in ufficio, e poi mi alzo puntualmente alle 13 per continuare a lavorare. Lavoro fino alle 17:30, poi raccolgo le mie cose e prendo l'autobus per <span class="code-blank" data-id="9-3" data-answer="casa"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（意大利语）",
        hint: "verbi, nomi e frasi",
        explanation: "Descrive una vita quotidiana completa dal risveglio al ritorno a casa dal lavoro",
        fullSentence: "Ogni giorno, dopo essermi svegliato, termino prima la mia routine mattutina come usare il bagno e lavarmi. Quindi scendo le scale e prendo l'autobus per l'azienda, con una corse in strada, e generalmente arrivo in tempo per il lavoro alle 9. Arrivando in ufficio, depongo prima lo zaino, navigo un po' sul mio computer personale, poi vado nel laboratorio per accendere il computer aziendale. Verifico i problemi che ho sollevato in precedenza e confermo se c'è qualcosa che deve essere testato di nuovo. Se è necessario un nuovo test, vado al banco di prova per svolgere il lavoro di prova e preparare contemporaneamente l'incontro con i capi e il team tedesco. Verso le 11:30, chiedo ai miei colleghi di andare a pranzo insieme. Discutiamo e scegliamo un tipo di cibo, ordinamo i piatti e a volte aspettiamo il cibo. Dopo il pasto, paghiamo il conto, asciughiamo la bocca, poi camminiamo con i colleghi per aiutare la digestione prima di tornare insieme all'azienda. Tornando all'azienda, faccio una breve pisolino sulla mia scrivania, sia nel laboratorio che in ufficio, e poi mi alzo puntualmente alle 13 per continuare a lavorare. Lavoro fino alle 17:30, poi raccolgo le mie cose e prendo l'autobus per casa."
    },
    {
        id: 10,
        type: "sentence",
        title: "完整的日常工作生活（葡萄牙语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Cada dia, após me levantar, termino primeiro a minha rotina matutina como usar o banheiro e me lavar. Em seguida, desço as escadas e pego o ônibus para a empresa, com uma <span class="code-blank" data-id="10-1" data-answer="correspondência"></span> no caminho, e geralmente chego no trabalho pontualmente às 9 horas. Chegando ao escritório, deixo primeiro a mochila, navego um pouco no meu computador pessoal, e depois vou ao laboratório para ligar o computador da empresa. Verifico os problemas que levantei anteriormente e confirmo se há algo que precisa ser testado novamente. Se um novo teste for necessário, vou ao banco de <span class="code-blank" data-id="10-2" data-answer="teste"></span> para realizar o trabalho de teste e preparar, ao mesmo tempo, a reunião com os líderes e a equipe alemã. Por volta das 11:30, convido meus colegas para ir jantar juntos. Discutimos e escolhemos um tipo de comida, pedimos os pratos e às vezes esperamos a comida chegar. Após a refeição, pagamos a conta, enxugamos a boca e, em seguida, caminhamos com os colegas para ajudar a digestão antes de voltarmos juntos à empresa. Voltando à empresa, faço uma pequena soneca no meu escritório, seja no laboratório ou no escritório, e depois me levanto pontualmente às 13 horas para continuar trabalhando. Trabalho até as 17:30, depois guardo as minhas coisas e pego o ônibus para a <span class="code-blank" data-id="10-3" data-answer="casa"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（葡萄牙语）",
        hint: "verbos, substantivos e frases",
        explanation: "Descreve uma vida diária completa do acordar até o retorno para casa do trabalho",
        fullSentence: "Cada dia, após me levantar, termino primeiro a minha rotina matutina como usar o banheiro e me lavar. Em seguida, desço as escadas e pego o ônibus para a empresa, com uma correspondência no caminho, e geralmente chego no trabalho pontualmente às 9 horas. Chegando ao escritório, deixo primeiro a mochila, navego um pouco no meu computador pessoal, e depois vou ao laboratório para ligar o computador da empresa. Verifico os problemas que levantei anteriormente e confirmo se há algo que precisa ser testado novamente. Se um novo teste for necessário, vou ao banco de teste para realizar o trabalho de teste e preparar, ao mesmo tempo, a reunião com os líderes e a equipe alemã. Por volta das 11:30, convido meus colegas para ir jantar juntos. Discutimos e escolhemos um tipo de comida, pedimos os pratos e às vezes esperamos a comida chegar. Após a refeição, pagamos a conta, enxugamos a boca e, em seguida, caminhamos com os colegas para ajudar a digestão antes de voltarmos juntos à empresa. Voltando à empresa, faço uma pequena soneca no meu escritório, seja no laboratório ou no escritório, e depois me levanto pontualmente às 13 horas para continuar trabalhando. Trabalho até as 17:30, depois guardo as minhas coisas e pego o ônibus para a casa."
    },
    {
        id: 11,
        type: "sentence",
        title: "完整的日常工作生活（荷兰语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Elke dag, na het opstaan, voltooi ik eerst mijn ochtendroutine zoals het gebruik van het toilet en het wassen. Daarna ga ik de trap af en neem de bus naar het bedrijf, met een <span class="code-blank" data-id="11-1" data-answer="overstap"></span> onderweg, en kom meestal om 9 uur op tijd aan bij het werk. Bij aankomst op kantoor leg ik eerst mijn rugzak neer, surf ik een beetje op mijn persoonlijke computer, en ga vervolgens naar het laboratorium om de bedrijfcomputer aan te zetten. Ik controleer de problemen die ik eerder heb aangekaart en bevestig of er iets moet worden getest. Als een nieuwe test nodig is, ga ik naar de testbank om het testwerk uit te voeren en tegelijkertijd voor te bereiden op het vergadering met de leiders en het Duitse team. Rond 11:30 vraag ik mijn collega's om samen naar de <span class="code-blank" data-id="11-2" data-answer="lunch"></span> te gaan. We bespreken en kiezen een type voedsel, bestellen de gerechten en wachten soms tot het voedsel komt. Na de maaltijd betalen we de rekening, vegen ons mond af, en gaan vervolgens met collega's wandelen om de vertering te helpen voordat we samen teruggaan naar het bedrijf. Terug bij het bedrijf neem ik een korte dutje op mijn bureau, ofwel in het laboratorium ofwel in het kantoor, en sta dan om 13 uur op tijd op om verder te werken. Ik werk tot 17:30, en pak vervolgens mijn spullen in en neem de bus naar <span class="code-blank" data-id="11-3" data-answer="thuis"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（荷兰语）",
        hint: "werkwoorden, zelfstandige naamwoorden en zinnen",
        explanation: "Beschrijft een volledige dagelijkse levensroutine van opstaan tot thuiskomen van het werk",
        fullSentence: "Elke dag, na het opstaan, voltooi ik eerst mijn ochtendroutine zoals het gebruik van het toilet en het wassen. Daarna ga ik de trap af en neem de bus naar het bedrijf, met een overstap onderweg, en kom meestal om 9 uur op tijd aan bij het werk. Bij aankomst op kantoor leg ik eerst mijn rugzak neer, surf ik een beetje op mijn persoonlijke computer, en ga vervolgens naar het laboratorium om de bedrijfcomputer aan te zetten. Ik controleer de problemen die ik eerder heb aangekaart en bevestig of er iets moet worden getest. Als een nieuwe test nodig is, ga ik naar de testbank om het testwerk uit te voeren en tegelijkertijd voor te bereiden op het vergadering met de leiders en het Duitse team. Rond 11:30 vraag ik mijn collega's om samen naar de lunch te gaan. We bespreken en kiezen een type voedsel, bestellen de gerechten en wachten soms tot het voedsel komt. Na de maaltijd betalen we de rekening, vegen ons mond af, en gaan vervolgens met collega's wandelen om de vertering te helpen voordat we samen teruggaan naar het bedrijf. Terug bij het bedrijf neem ik een korte dutje op mijn bureau, ofwel in het laboratorium ofwel in het kantoor, en sta dan om 13 uur op tijd op om verder te werken. Ik werk tot 17:30, en pak vervolgens mijn spullen in en neem de bus naar thuis."
    },
    {
        id: 12,
        type: "sentence",
        title: "完整的日常工作生活（瑞典语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Varje dag, efter att ha vaknat, slutför jag först min morgonrutin som att använda toaletten och tvätta mig. Sedan går jag nerför trappan och tar bussen till företaget, med en <span class="code-blank" data-id="12-1" data-answer="byten"></span> på vägen, och kommer vanligtvis på plats till jobbet kl. 9. När jag kommer till kontoret lägger jag först ner ryggsäcken, surfar lite på min personliga dator, och går sedan till laboratoriet för att slå på företagets dator. Jag kontrollerar de problem jag har lyft fram tidigare och bekräftar om det finns något som behöver testas igen. Om ett nytt test krävs går jag till testbänken för att utföra testarbetet och förbereda samtidigt för mötet med cheferna och det tyska teamet. Runt kl. 11:30 ber jag mina kollegor att gå och äta lunch tillsammans. Vi diskuterar och väljer en mattyp, beställer rätterna och väntar ibland på maten. Efter maten betalar vi räkningen, torkar munnen och går sedan och promenerar med kollegor för att hjälpa till med matsmältningen innan vi går tillbaka till företaget tillsammans. När jag återvänder till företaget tar jag en kort tupplur på min skrivbord, antingen i laboratoriet eller i kontoret, och står sedan upp punktligt kl. 13 för att fortsätta arbeta. Jag arbetar till kl. 17:30, packar sedan mina saker och tar bussen till <span class="code-blank" data-id="12-2" data-answer="hem"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（瑞典语）",
        hint: "verb, substantiv och meningar",
        explanation: "Beskriver en fullständig vardagsroutine från att vakna till att komma hem från jobbet",
        fullSentence: "Varje dag, efter att ha vaknat, slutför jag först min morgonrutin som att använda toaletten och tvätta mig. Sedan går jag nerför trappan och tar bussen till företaget, med en byten på vägen, och kommer vanligtvis på plats till jobbet kl. 9. När jag kommer till kontoret lägger jag först ner ryggsäcken, surfar lite på min personliga dator, och går sedan till laboratoriet för att slå på företagets dator. Jag kontrollerar de problem jag har lyft fram tidigare och bekräftar om det finns något som behöver testas igen. Om ett nytt test krävs går jag till testbänken för att utföra testarbetet och förbereda samtidigt för mötet med cheferna och det tyska teamet. Runt kl. 11:30 ber jag mina kollegor att gå och äta lunch tillsammans. Vi diskuterar och väljer en mattyp, beställer rätterna och väntar ibland på maten. Efter maten betalar vi räkningen, torkar munnen och går sedan och promenerar med kollegor för att hjälpa till med matsmältningen innan vi går tillbaka till företaget tillsammans. När jag återvänder till företaget tar jag en kort tupplur på min skrivbord, antingen i laboratoriet eller i kontoret, och står sedan upp punktligt kl. 13 för att fortsätta arbeta. Jag arbetar till kl. 17:30, packar sedan mina saker och tar bussen till hem."
    },
    {
        id: 13,
        type: "sentence",
        title: "完整的日常工作生活（越南语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Mỗi ngày, sau khi thức dậy, tôi hoàn thành trước tiên thói quen buổi sáng như đi vệ sinh và rửa mặt. Sau đó, tôi đi xuống cầu thang và bắt xe buýt đến công ty, với một <span class="code-blank" data-id="13-1" data-answer="lượt"></span> trên đường, và thường đến nơi làm việc đúng giờ lúc 9. Khi đến văn phòng, tôi đặt túi về trước, duyệt web một chút trên máy tính cá nhân, sau đó đi đến phòng thí nghiệm để bật máy tính công ty. Tôi kiểm tra các vấn đề đã nêu trước đó và xác nhận liệu có gì cần kiểm tra lại hay không. Nếu cần kiểm tra mới, tôi sẽ đến hệ thống <span class="code-blank" data-id="13-2" data-answer="kiểm tra"></span> để thực hiện công việc kiểm tra và đồng thời chuẩn bị cho cuộc họp với quản lý và nhóm Đức. Khoảng 11:30, tôi mời đồng nghiệp đi ăn trưa cùng nhau. Chúng tôi thảo luận và chọn loại thức ăn, đặt món và đôi khi chờ thức ăn đến. Sau bữa ăn, chúng tôi trả hóa đơn, lau miệng và sau đó đi dạo cùng đồng nghiệp để giúp tiêu hóa trước khi quay lại công ty cùng nhau. Quay lại công ty, tôi ngủ ngắn trên bàn làm việc, hoặc trong phòng thí nghiệm hoặc trong văn phòng, rồi dậy đúng giờ lúc 13 để tiếp tục làm việc. Tôi làm việc cho đến 17:30, sau đó đóng gói đồ đạc và bắt xe buýt về <span class="code-blank" data-id="13-3" data-answer="nhà"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（越南语）",
        hint: "động từ, danh từ và câu",
        explanation: "Mô tả một thói quen hàng ngày đầy đủ từ khi thức dậy đến khi về nhà từ công việc",
        fullSentence: "Mỗi ngày, sau khi thức dậy, tôi hoàn thành trước tiên thói quen buổi sáng như đi vệ sinh và rửa mặt. Sau đó, tôi đi xuống cầu thang và bắt xe buýt đến công ty, với một lượt trên đường, và thường đến nơi làm việc đúng giờ lúc 9. Khi đến văn phòng, tôi đặt túi về trước, duyệt web một chút trên máy tính cá nhân, sau đó đi đến phòng thí nghiệm để bật máy tính công ty. Tôi kiểm tra các vấn đề đã nêu trước đó và xác nhận liệu có gì cần kiểm tra lại hay không. Nếu cần kiểm tra mới, tôi sẽ đến hệ thống kiểm tra để thực hiện công việc kiểm tra và đồng thời chuẩn bị cho cuộc họp với quản lý và nhóm Đức. Khoảng 11:30, tôi mời đồng nghiệp đi ăn trưa cùng nhau. Chúng tôi thảo luận và chọn loại thức ăn, đặt món và đôi khi chờ thức ăn đến. Sau bữa ăn, chúng tôi trả hóa đơn, lau miệng và sau đó đi dạo cùng đồng nghiệp để giúp tiêu hóa trước khi quay lại công ty cùng nhau. Quay lại công ty, tôi ngủ ngắn trên bàn làm việc, hoặc trong phòng thí nghiệm hoặc trong văn phòng, rồi dậy đúng giờ lúc 13 để tiếp tục làm việc. Tôi làm việc cho đến 17:30, sau đó收拾 đồ đạc và bắt xe buýt về nhà."
    },
    {
        id: 14,
        type: "sentence",
        title: "完整的日常工作生活（缅甸语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>နေ့တိုင်း၊ နိုးလာပြီးနောက်၊ သန့်ရှင်းခြင်းနှင့် မျက်နှာဆေးကြောသော နံနက်ထုံးတမ်းစဉ်အတွက် ပထမဦးစွာ ပြီးဆုံးပါသည်။ ထို့နောက်၊ ကျွန်ုပ်သည် စက်ဘီးတိုင်းကို ဖြတ်ကျော်၍ ကုမ္ပဏီသို့ ဘတ်စ်ကားကို ခေါ်ယူသည်။ ကျွန်ုပ်သည် နေရာတစ်ခုခုပေါ်ရှိ <span class="code-blank" data-id="14-1" data-answer="လမ်း"> နှင့် တိုင်းတာရေးကို ခေါ်ယူသည်။ မကြာခဏ ၉ နာရီတွင် စတင်အလုပ်လုပ်သည်။ ရုံးတွင်ရောက်သောအခါ၊ ကျွန်ုပ်သည် ကျောရိုးစီးကို နေရာချပြီး ကိုယ်ပိုင်ကွန်ပျူတာတွင် အနည်းငယ် လေ့လာသည်။ ထို့နောက် ကုမ္ပဏီကွန်ပျူတာကို ဖွင့်ရန် ဓာတ်ခွဲခန်းသို့ သွားသည်။ ကျွန်ုပ်သည် ယခင်က ဖော်ပြခဲ့သော ပြဿနာများကို စစ်ဆေးပြီး နောက်ထပ်စစ်ဆေးရန် လိုအပ်ပါသလား စစ်ဆေးပါသည်။ အသစ်သောစစ်ဆေးမှုလိုအပ်လျှင်၊ ကျွန်ုပ်သည် စစ်ဆေးခန်းသို့သွားရန် စစ်ဆေးခန်းသို့သွားပြီး ညွှန်ကြားချက်များနှင့် ဂျာမန်အဖွဲ့နှင့် ညွှန်ကြားချက်များကို ပြင်ဆင်ပါသည်။ ၁၁:၃၀ ဝန်းကျင်တွင်၊ ကျွန်ုပ်သည် အလုပ်ဖော်များနှင့်အတူ နေ့လည်စာစားရန် ကျွန်ုပ်ကို တောင်းဆိုပါသည်။ ကျွန်ုပ်တို့သည် အစားအစာမျိုးကို ဆွေးနွေးကာ ရွေးချယ်ပြီး၊ မစားစရာများကို မှာယူကာ တစ်ခါတစ်ရံ စားစရာများ လာစောင့်ရသည်။ အစားအစာပြီးနောက်၊ ကျွန်ုပ်တို့သည် စာရင်းကို ပေးဆောင်ပြီး၊ ပါးစပ်ကို ချောဆေးကြောပြီး၊ ထို့နောက် ကျွန်ုပ်တို့သည် အလုပ်ခန်းတွင်သာယာချိန်ရရှိရန် အလုပ်ခန်းသို့ ပြန်သွားမည့်အကြိမ်မတိုင်မီ အစာချြမ်းခြင်းကို ကူညီရန် အလုပ်ဖော်များနှင့် လမ်းလျှောက်ရသည်။ ကုမ္ပဏီသို့ပြန်လာသည့်အခါ၊ ကျွန်ုပ်သည် ဓာတ်ခွဲခန်းသို့မဟုတ် ရုံးတွင် စာရေးပွဲတွင် အနည်းငယ် အိပ်စက်ပြီး ၁၃ နာရီတွင် အချိန်မီထွက်လာသည်။ ၁၇:၃၀ အထိ အလုပ်လုပ်ပြီး၊ ၎င်းနောက် ကျွန်ုပ်သည် ကိရိယာများကို ထုပ်ဆည်းပြီး ဘတ်စ်ကားထဲသို့ <span class="code-blank" data-id="14-2" data-answer="အိမ်"> ပြန်သွားသည်။</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（缅甸语）",
        hint: "ကြိယာများ၊ နာမ်များနှင့် ဝါကျများ",
        explanation: "နိုးလာပြီးနောက် အိမ်သို့ပြန်လာမည့်အထိ ပြည့်စုံသော နေ့စဉ်လုပ်ငန်းစဉ်ကို ဖော်ပြသည်။",
        fullSentence: "နေ့တိုင်း၊ နိုးလာပြီးနောက်၊ သန့်ရှင်းခြင်းနှင့် မျက်နှာဆေးကြောသော နံနက်ထုံးတမ်းစဉ်အတွက် ပထမဦးစွာ ပြီးဆုံးပါသည်။ ထို့နောက်၊ ကျွန်ုပ်သည် စက်ဘီးတိုင်းကို ဖြတ်ကျော်၍ ကုမ္ပဏီသို့ ဘတ်စ်ကားကို ခေါ်ယူသည်။ ကျွန်ုပ်သည် နေရာတစ်ခုခုပေါ်ရှိ လမ်း နှင့် တိုင်းတာရေးကို ခေါ်ယူသည်။ မကြာခဏ ၉ နာရီတွင် စတင်အလုပ်လုပ်သည်။ ရုံးတွင်ရောက်သောအခါ၊ ကျွန်ုပ်သည် ကျောရိုးစီးကို နေရာချပြီး ကိုယ်ပိုင်ကွန်ပျူတာတွင် အနည်းငယ် လေ့လာသည်။ ထို့နောက် ကုမ္ပဏီကွန်ပျူတာကို ဖွင့်ရန် ဓာတ်ခွဲခန်းသို့ သွားသည်။ ကျွန်ုပ်သည် ယခင်က ဖော်ပြခဲ့သော ပြဿနာများကို စစ်ဆေးပြီး နောက်ထပ်စစ်ဆေးရန် လိုအပ်ပါသလား စစ်ဆေးပါသည်။ အသစ်သောစစ်ဆေးမှုလိုအပ်လျှင်၊ ကျွန်ုပ်သည် စစ်ဆေးခန်းသို့သွားရန် စစ်ဆေးခန်းသို့သွားပြီး ညွှန်ကြားချက်များနှင့် ဂျာမန်အဖွဲ့နှင့် ညွှန်ကြားချက်များကို ပြင်ဆင်ပါသည်။ ၁၁:၃၀ ဝန်းကျင်တွင်၊ ကျွန်ုပ်သည် အလုပ်ဖော်များနှင့်အတူ နေ့လည်စာစားရန် ကျွန်ုပ်ကို တောင်းဆိုပါသည်။ ကျွန်ုပ်တို့သည် အစားအစာမျိုးကို ဆွေးနွေးကာ ရွေးချယ်ပြီး၊ မစားစရာများကို မှာယူကာ တစ်ခါတစ်ရံ စားစရာများ လာစောင့်ရသည်။ အစားအစာပြီးနောက်၊ ကျွန်ုပ်တို့သည် စာရင်းကို ပေးဆောင်ပြီး၊ ပါးစပ်ကို ချောဆေးကြောပြီး၊ ထို့နောက် ကျွန်ုပ်တို့သည် အလုပ်ခန်းတွင်သာယာချိန်ရရှိရန် အလုပ်ခန်းသို့ ပြန်သွားမည့်အကြိမ်မတိုင်မီ အစာချြမ်းခြင်းကို ကူညီရန် အလုပ်ဖော်များနှင့် လမ်းလျှောက်ရသည်။ ကုမ္ပဏီသို့ပြန်လာသည့်အခါ၊ ကျွန်ုပ်သည် ဓာတ်ခွဲခန်းသို့မဟုတ် ရုံးတွင် စာရေးပွဲတွင် အနည်းငယ် အိပ်စက်ပြီး ၁၃ နာရီတွင် အချိန်မီထွက်လာသည်။ ၁၇:၃၀ အထိ အလုပ်လုပ်ပြီး၊ ၎င်းနောက် ကျွန်ုပ်သည် ကိရိယာများကို ထုပ်ဆည်းပြီး ဘတ်စ်ကားထဲသို့ အိမ်ပြန်သွားသည်။"
    },
    {
        id: 15,
        type: "sentence",
        title: "完整的日常工作生活（希伯来语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>כל יום, אחרי שמתעורר, אני משלים תחילה את התהליך הבוקרי שלי כמו שימוש בשירותים וניקוי פנים. לאחר מכן, אני הולך מטה במדרגות ולקח את האוטובוס לחברה, עם <span class="code-blank" data-id="15-1" data-answer="מעבר"></span> בדרך, ודרך כלל מגיע לעבודה בזמן בשעה 9. כשהוגעתי למשרד, אני שם את העגלה מקודמת, גולש קצת באינטרנט במחשב האישי שלי, ואז הולך למעבדה כדי לפתוח את המחשב של החברה. אני בודק את הבעיות שהעלתי בעבר ו� מאשר אם יש משהו שצריך לבדוק שוב. אם יש צורך בבדיקה חדשה, אני הולך למערכת <span class="code-blank" data-id="15-2" data-answer="בדיקה"></span> לבצע את עבודת הבדיקה ולהכין באותו הזמן לפגישה עם המנהלים והקבוצה הגרמנית. בסביבות השעה 11:30, אני מזמין את הנהלים לאכול ארוחת צהריים יחד. אנו דנים ובחרנו בסוג של אוכל, הזמנינו את המנות ולפעמים המתינו לאוכל להגיע. אחרי הארוחה, אנו משלמים את החשבון, מנגבים את הפה ואז הולכים לטייל עם הנהלים כדי לעזור לעיכול לפני שאנחנו חוזרים לחברה יחד. כשהוחזרתי לחברה, אני ישן קצת על השולחן, או במעבדה או במשרד, ואז קם בזמן בשעה 13 כדי להמשיך לעבוד. אני עובד עד השעה 17:30, ואז אוסף את החפצים שלי ולקח את האוטובוס חזרה <span class="code-blank" data-id="15-3" data-answer="בית"></span>.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（希伯来语）",
        hint: "פועל, שם עצם ומשפטים",
        explanation: "מתאר תהליך יומי מלא משעת התעוררות ועד לחזרה הביתה ממקום העבודה",
        fullSentence: "כל יום, אחרי שמתעורר, אני משלים תחילה את התהליך הבוקרי שלי כמו שימוש בשירותים וניקוי פנים. לאחר מכן, אני הולך מטה במדרגות ולקח את האוטובוס לחברה, עם מעבר בדרך, ודרך כלל מגיע לעבודה בזמן בשעה 9. כשהוגעתי למשרד, אני שם את העגלה מקודמת, גולש קצת באינטרנט במחשב האישי שלי, ואז הולך למעבדה כדי לפתוח את המחשב של החברה. אני בודק את הבעיות שהעלתי בעבר ו� מאשר אם יש משהו שצריך לבדוק שוב. אם יש צורך בבדיקה חדשה, אני הולך למערכת בדיקה לבצע את עבודת הבדיקה ולהכין באותו הזמן לפגישה עם המנהלים והקבוצה הגרמנית. בסביבות השעה 11:30, אני מזמין את הנהלים לאכול ארוחת צהריים יחד. אנו דנים ובחרנו בסוג של אוכל, הזמנינו את המנות ולפעמים המתינו לאוכל להגיע. אחרי הארוחה, אנו משלמים את החשבון, מנגבים את הפה ואז הולכים לטייל עם הנהלים כדי לעזור לעיכול לפני שאנחנו חוזרים לחברה יחד. כשהוחזרתי לחברה, אני ישן קצת על השולחן, או במעבדה או במשרד, ואז קם בזמן בשעה 13 כדי להמשיך לעבודה. אני עובד עד השעה 17:30, ואז אוסף את החפצים שלי ולקח את האוטובוס חזרה בית."
    },
    {
        id: 16,
        type: "sentence",
        title: "完整的日常工作生活（藏语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>ཉིན་གཅིག་གི་ངོས་གཞི་འདི་ནང་། ང་རང་ཉིན་དགོངས་འབྲུག་སྟེ་ཉི་མ་གནས་སྟེང་གི་གྲུབ་འབྲས་དང་རྒྱུད་འཛིན་བྱེད་དགོས། དེ་རྗེས་ང་རང་ལ་ཐོག་མར་ལས་མིན་ནས་<span class="code-blank" data-id="16-1" data-answer="མཚོ"></span>དུ་ཡོང་བ་དང་། ལས་ཁང་དུ་ཡོང་བ་སྟེ་ང་རང་གི་ཁྲིམས་འཇུག་རྒྱུ་བརྒྱུད་འཛིན་བྱེད་དགོས། དེ་རྗེས་ང་རང་གི་ལས་ཁང་གི་<span class="code-blank" data-id="16-2" data-answer="ཀོན་པོ"></span>གྱི་དྲན་ལས་ལ་བརྒྱུད་འཛིན་བྱེད་དགོས། ལས་ཀ་མིན་ནས་ང་རང་གི་<span class="code-blank" data-id="16-3" data-answer="འཚོ"></span>དུ་ཡོང་བ་དང་ལོ་སར་གང་ང་རང་གི་ལས་ཁང་གི་ལས་ཀ་ལ་བརྒྱུད་འཛིན་བྱེད་དགོས།</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（藏语）",
        hint: "བྱ་ཐབས་དང་མིང་ཁྲིམས་",
        explanation: "ཉིན་གཅིག་གི་ལས་ཀ་དང་འཚོ་བའི་དགོངས་ལས་བྱ་ཐབས་འདི་བསྒྱུར་ནས་འཛིན་བྱས་པ་",
        fullSentence: "ཉིན་གཅིག་གི་ངོས་གཞི་འདི་ནང་། ང་རང་ཉིན་དགོངས་འབྲུག་སྟེ་ཉི་མ་གནས་སྟེང་གི་གྲུབ་འབྲས་དང་རྒྱུད་འཛིན་བྱེད་དགོས། དེ་རྗེས་ང་རང་ལ་ཐོག་མར་ལས་མིན་ནས་རང་གི་ལས་ཁང་གི་མཚོད་དུ་ཡོང་བ་དང་། ལས་ཁང་དུ་ཡོང་བ་སྟེ་ང་རང་གི་ཁྲིམས་འཇུག་རྒྱུ་བརྒྱུད་འཛིན་བྱེད་དགོས། དེ་རྗེས་ང་རང་གི་ལས་ཁང་གི་ཀོན་པོའི་དྲན་ལས་ལ་བརྒྱུད་འཛིན་བྱེད་དགོས། ལས་ཀ་མིན་ནས་ང་རང་གི་འཚོད་དུ་ཡོང་བ་དང་ལོ་སར་གང་ང་རང་གི་ལས་ཁང་གི་ལས་ཀ་ལ་བརྒྱུད་འཛིན་བྱེད་དགོས།"
    },
    {
        id: 17,
        type: "sentence",
        title: "完整的日常工作生活（蒙语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Нэг өдрийн цагт, би хичээллэн тэрч, өглөөний арга бүрлэгийг дуусгахад бэлдсэн, бэлдэгч, ухаалаг, ухаалагтай. Дараа нь би буудлын <span class="code-blank" data-id="17-1" data-answer="гарал"></span>дээрх автобусыг аваад ажил газраа очдог. Ажил газарт ирэхэд, би өөрийн хувь хүний компьютерийн хэсэгт цаашлаад ажилд орж, дээрх ажил газрын <span class="code-blank" data-id="17-2" data-answer="компьютери"></span>дээр ажиллахад бэлдэх. Бидний албан тушаалыг хуваалцаж, ажиллахад бэлдсэн, ажиллахад бэлдсэн, ажиллахад бэлдсэн. Өдрийн дараа, би автобусыг аваад <span class="code-blank" data-id="17-3" data-answer="хороо"></span>дээр буцаж, өдрийн ажиллагыг дуусгана.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（蒙语）",
        hint: " үйлдэл, үг",
        explanation: "Түүхний өдөр бүрд, би хичээллэн тэрч, өглөөний арга бүрлэгийг дуусгахад бэлдсэн, бэлдэгч, ухаалаг, ухаалагтай. Дараа нь би буудлын гарал дээрх автобусыг аваад ажил газраа очдог. Ажил газарт ирэхэд, би өөрийн хувь хүний компьютерийн хэсэгт цаашлаад ажилд орж, дээрх ажил газрын компьютери дээр ажиллахад бэлдэх. Бидний албан тушаалыг хуваалцаж, ажиллахад бэлдсэн, ажиллахад бэлдсэн, ажиллахад бэлдсэн. Өдрийн дараа, би автобусыг аваад хороо дээр буцаж, өдрийн ажиллагыг дуусгана.",
        fullSentence: "Нэг өдрийн цагт, би хичээллэн тэрч, өглөөний арга бүрлэгийг дуусгахад бэлдсэн, бэлдэгч, ухаалаг, ухаалагтай. Дараа нь би буудлын гарал дээрх автобусыг аваад ажил газраа очдог. Ажил газарт ирэхэд, би өөрийн хувь хүний компьютерийн хэсэгт цаашлаад ажилд орж, дээрх ажил газрын компьютери дээр ажиллахад бэлдэх. Бидний албан тушаалыг хуваалцаж, ажиллахад бэлдсэн, ажиллахад бэлдсэн, ажиллахад бэлдсэн. Өдрийн дараа, би автобусыг аваад хороо дээр буцаж, өдрийн ажиллагыг дуусгана."
    },
    {
        id: 18,
        type: "sentence",
        title: "完整的日常工作生活（印度尼西亚语）",
        content: `<div class="p-4 font-mono text-sm">
                    <div>Setiap hari, saya bangun tidur, mandi, dan makan sarapan. Kemudian, saya naik <span class="code-blank" data-id="18-1" data-answer="bis"></span> ke kantor. Di kantor, saya membuka laptop dan memulai pekerjaan. Pada siang hari, saya makan <span class="code-blank" data-id="18-2" data-answer="siang"></span> bersama rekan kerja. Setelah selesai bekerja, saya naik bis kembali ke <span class="code-blank" data-id="18-3" data-answer="rumah"></span> dan bersantai.</div>
                </div>`,
        instruction: "填写完整的日常工作生活句子（印度尼西亚语）",
        hint: "kata kerja, kata benda",
        explanation: "Deskripsi tentang rutinitas harian sehari-hari",
        fullSentence: "Setiap hari, saya bangun tidur, mandi, dan makan sarapan. Kemudian, saya naik bis ke kantor. Di kantor, saya membuka laptop dan memulai pekerjaan. Pada siang hari, saya makan siang bersama rekan kerja. Setelah selesai bekerja, saya naik bis kembali ke rumah dan bersantai."
    }
];