// 打字游戏句子库
const contentList = [
    { en: "Stay hungry, stay foolish.", cn: "求知若饥，虚心若愚。" },
    { en: "Talk is cheap. Show me the code.", cn: "空谈误国，实干兴邦 (代码见真章)。" },
    { en: "Hello World", cn: "你好，世界 (编程起点)" },
    { en: "Consistency is key.", cn: "持之以恒是关键。" },
    { en: "artificial intelligence", cn: "人工智能" },
    { en: "The only way to do great work is to love what you do.", cn: "成就伟业的唯一途径是热爱你的工作。" },
    { en: "function execution", cn: "函数执行" },
    { en: "debug the universe", cn: "调试宇宙" },
    { en: "Simplicity is the ultimate sophistication.", cn: "至繁归于至简。" },
    { en: "creative flow state", cn: "创造性心流状态" },
    { en: "Don't repeat yourself.", cn: "不要重复造轮子 (DRY原则)。" },
    // 新增句子
    { en: "Practice makes perfect.", cn: "熟能生巧。" },
    { en: "Time is money.", cn: "时间就是金钱。" },
    { en: "Knowledge is power.", cn: "知识就是力量。" },
    { en: "Think outside the box.", cn: "跳出思维定式。" },
    { en: "The sky is the limit.", cn: "天空才是极限。" },
    { en: "Every cloud has a silver lining.", cn: "乌云背后有阳光。" },
    { en: "Actions speak louder than words.", cn: "行动胜于言语。" },
    { en: "Better late than never.", cn: "亡羊补牢，为时未晚。" },
    { en: "Where there is a will, there is a way.", cn: "有志者事竟成。" },
    { en: "Fortune favors the bold.", cn: "幸运眷顾勇者。" },
    { en: "No pain, no gain.", cn: "不劳无获。" },
    { en: "Strike while the iron is hot.", cn: "趁热打铁。" },
    { en: "Rome wasn't built in a day.", cn: "罗马不是一天建成的。" },
    { en: "All good things come to those who wait.", cn: "耐心等待，好事将至。" },
    { en: "Coding is fun.", cn: "编程很有趣。" },
    { en: "JavaScript is versatile.", cn: "JavaScript用途广泛。" },
    { en: "Learning never stops.", cn: "学习永不止步。" },
    { en: "Focus on progress, not perfection.", cn: "关注进步，而非完美。" },
    { en: "Failure is the mother of success.", cn: "失败是成功之母。" },
    { en: "Teamwork makes the dream work.", cn: "团队合作成就梦想。" },
    { en: "Life is like riding a bicycle.", cn: "生活就像骑自行车。" },
    { en: "The best way to predict the future is to invent it.", cn: "预测未来的最佳方式是创造它。" },
    { en: "Innovation distinguishes between a leader and a follower.", cn: "创新区分领导者和跟随者。" },
    { en: "Your time is limited, don't waste it living someone else's life.", cn: "你的时间有限，不要浪费在过别人的生活上。" },
    // 新增句子
    { en: "The journey of a thousand miles begins with a single step.", cn: "千里之行，始于足下。" },
    { en: "Do what you can, with what you have, where you are.", cn: "在你所处的位置，用你所拥有的，做你能做的。" },
    { en: "The early bird catches the worm.", cn: "早起的鸟儿有虫吃。" },
    { en: "A picture is worth a thousand words.", cn: "一张图片胜过千言万语。" },
    { en: "When life gives you lemons, make lemonade.", cn: "当生活给你柠檬时，就做柠檬水。" },
    { en: "Haste makes waste.", cn: "欲速则不达。" },
    { en: "Better safe than sorry.", cn: "安全第一。" },
    { en: "Two heads are better than one.", cn: "三个臭皮匠，顶个诸葛亮。" },
    { en: "A stitch in time saves nine.", cn: "小洞不补，大洞吃苦。" },
    { en: "Look before you leap.", cn: "三思而后行。" },
    { en: "Unity is strength.", cn: "团结就是力量。" },
    { en: "Knowledge without practice is useless.", cn: "光有知识没有实践是没用的。" },
    { en: "Patience is a virtue.", cn: "耐心是一种美德。" },
    { en: "Hard work pays off.", cn: "努力终有回报。" },
    { en: "Quality over quantity.", cn: "质量胜于数量。" },
    { en: "Honesty is the best policy.", cn: "诚实是最好的策略。" },
    { en: "Respect yourself and others will respect you.", cn: "尊重自己，别人才会尊重你。" },
    { en: "Success comes from hard work and determination.", cn: "成功来自努力和决心。" },
    { en: "Experience is the best teacher.", cn: "经验是最好的老师。" },
    { en: "Nothing is impossible to a willing heart.", cn: "心之所愿，无事不成。" },
    { en: "The grass is always greener on the other side.", cn: "这山望着那山高。" },
    { en: "Practice what you preach.", cn: "言行一致。" },
    { en: "Live and let live.", cn: "自己活也让别人活。" },
    { en: "Time heals all wounds.", cn: "时间治愈一切创伤。" },
    { en: "Actions speak louder than words.", cn: "事实胜于雄辩。" },
    { en: "A friend in need is a friend indeed.", cn: "患难见真情。" },
    { en: "An apple a day keeps the doctor away.", cn: "一天一个苹果，医生远离我。" },
    { en: "You are never too old to learn.", cn: "活到老，学到老。" },
    { en: "Laughter is the best medicine.", cn: "笑是最好的药。" },
    { en: "To err is human.", cn: "人非圣贤，孰能无过。" },
    { en: "Simplicity is the key to brilliance.", cn: "简洁是卓越的关键。" }
];

// 导出内容供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = contentList;
}